In [38]:
import numpy as np
import scipy
import scipy.linalg
import pprint

In [39]:
#AUXILIARES
def imprime_status(col_actual, P,L,U):
    print("\n===========================")
    print("ITERACION:  ", col_actual)
    print("Matriz L")
    print(L)
    print("Matriz U")
    print(U)
    print("Matriz P")
    print(P)
    
def intercambio_filas(M, a, b):
    fila_aux = M[a, :].copy()
    M[a, :] =  M[b, :]
    M[b, :] = fila_aux
    return M

In [40]:
def nuestro_lup(A):
    """
     Parameters
    ----------   
    A : ndarray
        2D array containing data with `float` type.
       
    Returns
    -------
    L
        ndarray of matrix L un LUP factorization
    U
        ndarray of matrix U un LUP factorization
    P
        ndarray of matrix P un LUP factorization
    """
    n = len(A)
    L = np.zeros((n,n), dtype=np.float)
    U = A.copy()
    P =  np.identity(n, dtype=np.float) 

    for col_actual in range(n):
        #imprime_status(col_actual, P,L,U)

        #Get maximum row to swap values
        row_mayor = col_actual
        a_hat = abs(U[col_actual,col_actual])
        for row in range(col_actual, n): 
            a = abs(U[row, col_actual])
            if a > a_hat : 
                row_mayor = row
                a_hat = a

        #Swap values
        U = intercambio_filas(U, row_mayor, col_actual)
        L = intercambio_filas(L, row_mayor, col_actual)
        P = intercambio_filas(P, row_mayor, col_actual) 


        for j in range(col_actual+1, n):
            vj = U[col_actual, col_actual]
            if (vj !=0):
                multi =  U[j, col_actual] / vj
                L[j, col_actual] =  multi
                U[j, :] = U[j, :] - multi * U[col_actual, :]

    L = L + np.identity(n, dtype=np.float)
    return L, U, P

In [42]:
#Segunda opción que jala para cualquier matriz
def PLU(A):
    L,U,P=nuestro_lup(A)
    P_correcta, L_correcta, U_correcta = scipy.linalg.lu(A)
    
    if ((P==P_correcta).all() and (L==L_correcta).all() and (U==U_correcta).all()):
        print("Correcto")
    else:
        print("Incorrecto para A igual a:")
        pprint.pprint(A)
        print("P algoritmo:")
        pprint.pprint(P)
        print("P correcta:")
        pprint.pprint(P_correcta)
        print("L algoritmo:")
        pprint.pprint(L)
        print("L correcta:")
        pprint.pprint(L_correcta)
        print("U algoritmo:")
        pprint.pprint(U)
        print("U correcta:")
        pprint.pprint(U_correcta)
        

In [46]:
for i in range(0,3):
    n=np.random.randint(2, 7)
    A=np.matrix(np.random.randint(-99,99, size=(n, n)))
    try:
        A_inv=np.linalg.inv(A)
        if (np.allclose(np.dot(A, A_inv), np.eye(n)))==True:
            PLU(A)
    except:
        print('Matriz Singular')

Incorrecto para A igual a:
matrix([[ 74,  63, -84],
        [ 17,  -3,  77],
        [ 41, -60,  72]])
P algoritmo:
array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])
P correcta:
array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])
L algoritmo:
array([[1.        , 0.        , 0.        ],
       [0.55405405, 1.        , 0.        ],
       [0.22972973, 0.18085106, 1.        ]])
L correcta:
array([[1.        , 0.        , 0.        ],
       [0.55405405, 1.        , 0.        ],
       [0.22972973, 0.18410935, 1.        ]])
U algoritmo:
matrix([[ 74,  63, -84],
        [  0, -94, 118],
        [  0,   0,  74]])
U correcta:
array([[ 74.        ,  63.        , -84.        ],
       [  0.        , -94.90540541, 118.54054054],
       [  0.        ,   0.        ,  74.47287484]])
Incorrecto para A igual a:
matrix([[ 65,  -9],
        [  3, -79]])
P algoritmo:
array([[1., 0.],
       [0., 1.]])
P correcta:
array([[1., 0.],
       [0., 1.]])
L algoritmo:
array([[1.      