## Algoritmo 
(se considera que los índices de los arrays inician en el valor $1$ y no en el $0$)

Entrada: $A \in \mathbb{R}^{n \times n}$.

Salida: factores $L, U \in \mathbb{R}^{n \times n}$, vector $piv \in \mathbb{R}^{n}$. El vector $piv$ se utiliza para construir a la matriz $P$.

Inicializar L con matriz identidad. Inicializar U como una matriz de ceros.

Para $j$ de $1$ a $n$ hacer:

Si $j$ es 1 definir $v = A(:,1)$ # v es la primer columna de $A$.

En otro caso:

Calcular $\hat{a} = P_{j-1} \cdots P_1 A(:,j)$ #aquí se utiliza al vector $piv$ para evitar hacer multiplicaciones de matriz vector, sólo se realizan intercambio de renglones

Resolver $L(1:j-1,1:j-1)z = \hat{a}(1:j-1)$ para $z \in \mathbb{R}^{j-1}$ por sustitución hacia delante

Definir $U(1:j-1,j) = z$

Definir $v(j:n) = \hat{a}(j:n) - L(j:n, 1:j-1)*z$

Determinar $\mu$ con $ j \leq \mu \leq n$ tal que $|v(\mu)| = ||v(j:n)||_\infty$

Definir $piv(j)=\mu$ # piv es un vector de tamaño $n-1$

$v(j) \leftrightarrow v(\mu)$ # $\leftrightarrow$ significa intercambiar $j$-ésima entrada de $v$ por $\mu$-ésima entrada de $v$.

$L(j,1:j-1) \leftrightarrow L(\mu,1:j-1)$ #$\leftrightarrow$ significa intercambio

Definir $U(j,j) = v(j)$.

Si $v(j) \neq 0 $ definir $L(j+1:n,j) = v(j+1:n)/v(j)$


In [1]:
import numpy as np

In [28]:
#AUXILIARES
def imprime_status(col_actual, P,L,U,A):
    print("\n===========================")
    print("ITERACION:  ", col_actual)
    print("Matriz A")
    print(A)
    print("Matriz L")
    print(L)
    print("Matriz U")
    print(U)
    print("Matriz P")
    print(P)
    
def intercambio_filas(M, a, b):
    fila_aux = M[a, :].copy()
    M[a, :] =  M[b, :]
    M[b, :] = fila_aux
    return M
    

In [31]:
#Entrada:  𝐴∈ℝ𝑛×𝑛 .
#Salida: factores  𝐿,𝑈∈ℝ𝑛×𝑛 , vector  𝑝𝑖𝑣∈ℝ𝑛 . El vector  𝑝𝑖𝑣  se utiliza para construir a la matriz  𝑃 .


"""
 Parameters
    ----------
   n : int
       matrix dimension
"""


A = np.array([[ 1, 4,-2], \
              [-3, 9, 8],
              [ 5, 1,-6]], dtype=np.float)

n = len(A)

#======================================================================
#Paso 1: encontrar factores  𝑃,𝐿,𝑈  tales que  𝑃𝐴=𝐿𝑈 
#======================================================================

#Inicializar L con matriz identidad. Inicializar U como una matriz de ceros.
L = np.identity(n, dtype=np.float)
U = A.copy()

P =  np.identity(n, dtype=np.float) #Tambien vamos a inicializar en la identidad
#Para  𝑗  de  1  a  𝑛  hacer:
for col_actual in range(n):
    imprime_status(col_actual, P,L,U,A)
    #Calcular  𝑎̂ =𝑃𝑗−1⋯𝑃1𝐴(:,𝑗)  #aquí se utiliza al vector  𝑝𝑖𝑣  para evitar hacer multiplicaciones de matriz vector, sólo se realizan intercambio de renglones
    #en la primer columna el pivote que es el elemento con máxima magnitud
    #BUSCAMOS ELEMENTO MAYOR EN COLUMNA
    row_mayor = j
    a_hat = abs(A[col_actual,col_actual])
    for row in range(col_actual, n): #Recorremos desde j
        a = abs(A[row, col_actual])
        if a > a_hat : 
            row_mayor = row
            a_hat = a

    #INTERCAMBIAMOS COLUMNAS
    #Para A
    A = intercambio_filas(A, row_mayor, col_actual)

    #$L(j,1:j-1) \leftrightarrow L(\mu,1:j-1)$ #$\leftrightarrow$ significa intercambio
    L = intercambio_filas(L, row_mayor, col_actual)

    #Para P
    #𝑣(𝑗)↔𝑣(𝜇)  #  ↔  significa intercambiar  𝑗 -ésima entrada de  𝑣  por  𝜇 -ésima entrada de  𝑣 .
    P = intercambio_filas(P, row_mayor, col_actual) 


    #Si  𝑣(𝑗)≠0  definir  𝐿(𝑗+1:𝑛,𝑗)=𝑣(𝑗+1:𝑛)/𝑣(𝑗)
    for j in range(col_actual + 1, n):
        multi = - U[j, col_actual] / U[col_actual, col_actual]
        L[j, col_actual] = - multi
        U[j, :] = U[j, :] + multi * U[col_actual, :]




ITERACION:   0
Matriz A
[[ 1.  4. -2.]
 [-3.  9.  8.]
 [ 5.  1. -6.]]
Matriz L
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Matriz U
[[ 1.  4. -2.]
 [-3.  9.  8.]
 [ 5.  1. -6.]]
Matriz P
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

ITERACION:   1
Matriz A
[[ 5.  1. -6.]
 [-3.  9.  8.]
 [ 1.  4. -2.]]
Matriz L
[[ 0.  0.  1.]
 [-3.  1.  0.]
 [ 5.  0.  0.]]
Matriz U
[[  1.   4.  -2.]
 [  0.  21.   2.]
 [  0. -19.   4.]]
Matriz P
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]

ITERACION:   2
Matriz A
[[ 5.  1. -6.]
 [ 1.  4. -2.]
 [-3.  9.  8.]]
Matriz L
[[ 0.         0.         1.       ]
 [ 5.         0.         0.       ]
 [-3.        -0.9047619  0.       ]]
Matriz U
[[ 1.          4.         -2.        ]
 [ 0.         21.          2.        ]
 [ 0.          0.          5.80952381]]
Matriz P
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]


### ¿Dado el sistema $Ax=b$, $A \in \mathbb{R}^{n \times n}$ cómo se resuelve con la factorización $PLU$?
Paso 1: encontrar factores $P,L,U$ tales que $PA=LU$.

Paso 2: resolver con el método de sustitución hacia delante el sistema triangular inferior $Ld=Pb$.

Paso 3: resolver con el método de sustitución hacia atrás el sistema triangular superior $Ux=d$.

In [ ]:
# COSAS QUE PODEMOS USAR EN EL FUTURO
for col_actual in range(n):
    #Si  𝑗  es 1 definir  𝑣=𝐴(:,1)  # v es la primer columna de  𝐴 .
    if col_actual == 0 :
        v = A[:,0] #Python empieza en 0
    #En otro caso:
    else:
        #Calcular  𝑎̂ =𝑃𝑗−1⋯𝑃1𝐴(:,𝑗)  #aquí se utiliza al vector  𝑝𝑖𝑣  para evitar hacer multiplicaciones de matriz vector, sólo se realizan intercambio de renglones
      