## Algoritmo 
(se considera que los índices de los arrays inician en el valor $1$ y no en el $0$)

Entrada: $A \in \mathbb{R}^{n \times n}$.

Salida: factores $L, U \in \mathbb{R}^{n \times n}$, vector $piv \in \mathbb{R}^{n}$. El vector $piv$ se utiliza para construir a la matriz $P$.

Inicializar L con matriz identidad. Inicializar U como una matriz de ceros.

Para $j$ de $1$ a $n$ hacer:

Si $j$ es 1 definir $v = A(:,1)$ # v es la primer columna de $A$.

En otro caso:

Calcular $\hat{a} = P_{j-1} \cdots P_1 A(:,j)$ #aquí se utiliza al vector $piv$ para evitar hacer multiplicaciones de matriz vector, sólo se realizan intercambio de renglones

Resolver $L(1:j-1,1:j-1)z = \hat{a}(1:j-1)$ para $z \in \mathbb{R}^{j-1}$ por sustitución hacia delante

Definir $U(1:j-1,j) = z$

Definir $v(j:n) = \hat{a}(j:n) - L(j:n, 1:j-1)*z$

Determinar $\mu$ con $ j \leq \mu \leq n$ tal que $|v(\mu)| = ||v(j:n)||_\infty$

Definir $piv(j)=\mu$ # piv es un vector de tamaño $n-1$

$v(j) \leftrightarrow v(\mu)$ # $\leftrightarrow$ significa intercambiar $j$-ésima entrada de $v$ por $\mu$-ésima entrada de $v$.

$L(j,1:j-1) \leftrightarrow L(\mu,1:j-1)$ #$\leftrightarrow$ significa intercambio

Definir $U(j,j) = v(j)$.

Si $v(j) \neq 0 $ definir $L(j+1:n,j) = v(j+1:n)/v(j)$


In [3]:
import numpy as np

In [27]:
#AUXILIARES
def imprime_status(col_actual, P,L,U):
    print("\n===========================")
    print("ITERACION:  ", col_actual)
    print("Matriz L")
    print(L)
    print("Matriz U")
    print(U)
    print("Matriz P")
    print(P)
    
def intercambio_filas(M, a, b):
    fila_aux = M[a, :].copy()
    M[a, :] =  M[b, :]
    M[b, :] = fila_aux
    return M
    

In [33]:
#Entrada:  𝐴∈ℝ𝑛×𝑛 .
#Salida: factores  𝐿,𝑈∈ℝ𝑛×𝑛 , vector  𝑝𝑖𝑣∈ℝ𝑛 . El vector  𝑝𝑖𝑣  se utiliza para construir a la matriz  𝑃 .


"""
 Parameters
    ----------
   n : int
       matrix dimension
"""


A = np.array([[ 1, 4,-2], \
              [-3, 9, 8],
              [ 5, 1,-6]], dtype=np.float)

n = len(A)

#======================================================================
#Paso 1: encontrar factores  𝑃,𝐿,𝑈  tales que  𝑃𝐴=𝐿𝑈 
#======================================================================

#Inicializar L con matriz identidad. Inicializar U como una matriz de ceros.
L = np.zeros((n,n), dtype=np.float)
U = A.copy()

P =  np.identity(n, dtype=np.float) #Tambien vamos a inicializar en la identidad
#Para  𝑗  de  1  a  𝑛  hacer:
for col_actual in range(n):
    imprime_status(col_actual, P,L,U)
    #Calcular  𝑎̂ =𝑃𝑗−1⋯𝑃1𝐴(:,𝑗)  #aquí se utiliza al vector  𝑝𝑖𝑣  para evitar hacer multiplicaciones de matriz vector, sólo se realizan intercambio de renglones
    #en la primer columna el pivote que es el elemento con máxima magnitud
    #BUSCAMOS ELEMENTO MAYOR EN COLUMNA
    row_mayor = col_actual
    a_hat = abs(U[col_actual,col_actual])
    for row in range(col_actual, n): #Recorremos desde j
        a = abs(U[row, col_actual])
        if a > a_hat : 
            row_mayor = row
            a_hat = a
    print("maximo: ", a_hat)
    print("Intecambio: ", row_mayor, " con ", col_actual)
    #INTERCAMBIAMOS COLUMNAS

    #Para U
    U = intercambio_filas(U, row_mayor, col_actual)

    #$L(j,1:j-1) \leftrightarrow L(\mu,1:j-1)$ #$\leftrightarrow$ significa intercambio
    L = intercambio_filas(L, row_mayor, col_actual)

    #Para P
    #𝑣(𝑗)↔𝑣(𝜇)  #  ↔  significa intercambiar  𝑗 -ésima entrada de  𝑣  por  𝜇 -ésima entrada de  𝑣 .
    P = intercambio_filas(P, row_mayor, col_actual) 


    #Si  𝑣(𝑗)≠0  definir  𝐿(𝑗+1:𝑛,𝑗)=𝑣(𝑗+1:𝑛)/𝑣(𝑗)
    for j in range(col_actual+1, n):
        multi = - U[j, col_actual] / U[col_actual, col_actual]
        print("VALOR DE j ", j, " VALOR DE COL_ACTUAL ", col_actual)
        print("VALOR De U[j, col_actual]", U[j, col_actual])
        print("VALOR De U[col_actual, col_actual]", U[col_actual, col_actual])
        print("VALOR MULTI: ", multi)
        L[j, col_actual] = - multi
        U[j, :] = U[j, :] + multi * U[col_actual, :]
        print("VALOR DE U[j, :]",U[j, :])

imprime_status(col_actual, P,L,U)
L = L + np.identity(n, dtype=np.float)
imprime_status(col_actual, P,L,U)


ITERACION:   0
Matriz L
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Matriz U
[[ 1.  4. -2.]
 [-3.  9.  8.]
 [ 5.  1. -6.]]
Matriz P
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
maximo:  5.0
Intecambio:  2  con  0
VALOR DE j  1  VALOR DE COL_ACTUAL  0
VALOR De U[j, col_actual] -3.0
VALOR De U[col_actual, col_actual] 5.0
VALOR MULTI:  0.6
VALOR DE U[j, :] [0.  9.6 4.4]
VALOR DE j  2  VALOR DE COL_ACTUAL  0
VALOR De U[j, col_actual] 1.0
VALOR De U[col_actual, col_actual] 5.0
VALOR MULTI:  -0.2
VALOR DE U[j, :] [ 0.   3.8 -0.8]

ITERACION:   1
Matriz L
[[ 0.   0.   0. ]
 [-0.6  0.   0. ]
 [ 0.2  0.   0. ]]
Matriz U
[[ 5.   1.  -6. ]
 [ 0.   9.6  4.4]
 [ 0.   3.8 -0.8]]
Matriz P
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
maximo:  9.6
Intecambio:  1  con  1
VALOR DE j  2  VALOR DE COL_ACTUAL  1
VALOR De U[j, col_actual] 3.8
VALOR De U[col_actual, col_actual] 9.6
VALOR MULTI:  -0.3958333333333333
VALOR DE U[j, :] [ 0.          0.         -2.54166667]

ITERACION:   2
Matriz L
[[ 0.          0.          0.        

In [2]:
from scipy.linalg import lu

In [10]:
p, l, u = lu(A)

print("Matriz L")
print(l)
print("Matriz U")
print(u)
print("Matriz P")
print(p)

Matriz L
[[ 1.    0.    0.    0.  ]
 [ 0.2   1.    0.    0.  ]
 [ 0.    0.1   1.    0.  ]
 [-0.5   0.    0.25  1.  ]]
Matriz U
[[12.  2.  1.  0.]
 [ 0. 10. -2.  2.]
 [ 0.  0. 15.  1.]
 [ 0.  0.  0. 10.]]
Matriz P
[[0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


### ¿Dado el sistema $Ax=b$, $A \in \mathbb{R}^{n \times n}$ cómo se resuelve con la factorización $PLU$?
Paso 1: encontrar factores $P,L,U$ tales que $PA=LU$.

Paso 2: resolver con el método de sustitución hacia delante el sistema triangular inferior $Ld=Pb$.

Paso 3: resolver con el método de sustitución hacia atrás el sistema triangular superior $Ux=d$.

In [ ]:
# COSAS QUE PODEMOS USAR EN EL FUTURO
for col_actual in range(n):
    #Si  𝑗  es 1 definir  𝑣=𝐴(:,1)  # v es la primer columna de  𝐴 .
    if col_actual == 0 :
        v = A[:,0] #Python empieza en 0
    #En otro caso:
    else:
        #Calcular  𝑎̂ =𝑃𝑗−1⋯𝑃1𝐴(:,𝑗)  #aquí se utiliza al vector  𝑝𝑖𝑣  para evitar hacer multiplicaciones de matriz vector, sólo se realizan intercambio de renglones
      