# Revisión primer algoritmo

Nombre del scrip : FactorizacionPLU

### 1.1 General 

#### 1) ¿Se entiende que objetivo del algoritmo?

Si fuera una persona usuaria, me tomaría trabajo saber cual es objetivo del algoritmo. Me parece que es necesario dar una pequeña introducción al principio para tener una idea de lo que se desarrollara despúes.

Propuesta: 
En este notebook se busca realizar la factorización PLU, la cual es un método para resolver sistemas de ecuaciones de distintas dimesiones ( pj matrices). Y el algoritmo se encarga de econtrar 3 matrices que nos ayudaran a resolver un sistema de ecuaciones. Las matrices que debería devolver el algoritmo son las siguientes:

L es una matriz triangular inferior, ejemplo:

$$L = \begin{bmatrix} 2& 0&0 \\ 1& 6& 0 \\ 1& 4& 1\end{bmatrix}$$

U es una matriz triangular superior, ejemplo:

$$U = \begin{bmatrix} 2& -1&7 \\ 0& 6& 2 \\ 0& 0& 5\end{bmatrix}$$

P es una matriz de pivote y en ella se queda registrado el intercambio de columnas, ejemplo

$$P = \begin{bmatrix} 1& 0&0 \\ 0& 1& 0 \\ 0& 0& 1\end{bmatrix}$$

#### 2) ¿El código tiene documentación entendible de lo que hacen las funciones?

Hasta el momento 2 funciones, falta documentación en la función: intercambio_filas. Se entiende lo que hace pero no estaría de más una pequeña documentación. De igual forma considero que esta función debe hacerse un modulo para posteriormente solo importarla.

#### 3) ¿Se utilizan todas las funciones?

No, hay una función que llama : imprime_status y no se utiliza en la implementación. Creo sería bueno borrarla para el algoritmo definitivo.

#### 4) ¿El nombre de las funciones es adecuado o entendible?

Solo recomendaría cambiar el nombre de la función más importante, que actualmente se llama nuestro_lup, podría ser algo como "PLU_factorization" para que sea más formal.

#### 5) ¿El código es entendible? 

Considero que si es ententible, realmente es un algoritmo pequeño y otra cosa que es amigable a la vista es que se esta utilizando la notación "snake_case".

### 1.2 Funcionalidad

Definire una función para ver si el algoritmo es correcto, de forma que tenga pruebas variadas y suficientes.

In [54]:
import numpy as np
import scipy
import pprint
from scipy.linalg import lu
from plu import nuestro_lup,intercambio_filas   #Hice un modulo de la funcion plu

In [47]:
def funcionalidad_invertible(A):
    """
     Parameters
    ----------   
    A : ndarray
        np.random la dimension de la matriz es un random entre 2 y 7.
       
    Returns
    -------
    Con esta función se comprueba que las matrices que 
     arroja el algoritmo PLU cumplen con el teorema, es decir que todas sean invertibles o no singulares
    """
        
    L,U,P=nuestro_lup(A)
    
    L_inv = np.linalg.inv(L)
    if (L_inv.all()==np.linalg.inv(L).all()):
        print("La matriz L obtenida es invertible y cumple con el teorema")
        pprint.pprint(L)
    else:
        print("La matriz L obtenida es incorrecta")
        pprint.pprint(L)
        
    U_inv = np.linalg.inv(U)
    if (U_inv.all()==np.linalg.inv(U).all()):
        print("La matriz U obtenida es invertible y cumple con el teorema")
        pprint.pprint(U)
    else:
        print("La matriz U obtenida es incorrecta")
        pprint.pprint(U)
    
    P_inv = np.linalg.inv(P)    
    if (P_inv.all()==np.linalg.inv(P).all()):
        print("La matriz P obtenida es invertible y cumple con el teorema")
        pprint.pprint(P)
    else:
        print("La matriz P obtenida es incorrecta")
        pprint.pprint(P)

In [97]:
n=np.random.randint(2, 10)
A=np.matrix(np.random.randint(-90,99, size=(n, n)))
funcionalidad_invertible(A)

La matriz L obtenida es invertible y cumple con el teorema
array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.6122449 ,  1.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [-0.19387755, -0.74603175,  1.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [-0.37755102,  0.53968254, -0.86567164,  1.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.59183673, -0.26984127, -0.25373134, -0.85964912,  1.        ,
         0.        ,  0.        ],
       [ 0.2244898 , -0.3968254 , -0.11940299,  0.53508772, -0.11881188,
         1.        ,  0.        ],
       [ 0.70408163,  0.14285714, -0.57462687,  0.47368421,  0.52475248,
        -0.58415842,  1.        ]])
La matriz U obtenida es invertible y cumple con el teorema
matrix([[  98,    2,   24,  -33,   91,  -52,  -38],
        [   0,   63,   81,   41,  -53,   83,    4],
        [   0,    0, 

In [228]:
from scipy.linalg import lu
def funcionalidad_exactitud(A):
    """
     Parameters
    ----------   
    A : ndarray
        np.random la dimension de la matriz es un random entre 2 y 7.
       
    Returns
    -------
    Con esta función se comprueba que las matrices sean exactas, se hace una compración con el paquete
    de python "scipy" que ya resuleve el algoritmo PLU.
    """
        
    L,U,P=nuestro_lup(A)
    P_c,L_c,U_c=scipy.linalg.lu(A)

    if ((L== L_c).all()):
        print("La matriz L es exacta")

    else:
        print("La matriz L es inexacta")
        pprint.pprint(L)
        pprint.pprint(L_c)

    if ((U== U_c).all()):
        print("La matriz U es exacta")

    else:
        print("La matriz U inexacta")
        pprint.pprint(U)
        pprint.pprint(U_c)
        
    if ((P== P_c).all()):
        print("La matriz P es exacta")

    else:
        print("La matriz P es inexacta")
        pprint.pprint(P)
        pprint.pprint(P_c)

In [243]:
n=np.random.randint(2, 10)
A=np.matrix(np.random.randint(-99,99, size=(n, n)))
funcionalidad_exactitud(A)

La matriz L es exacta
La matriz U inexacta
matrix([[ 32, -68],
        [  0, -33]])
array([[ 32. , -68. ],
       [  0. , -33.5]])
La matriz P es exacta


In [253]:
n=np.random.randint(2, 10)
A=np.matrix(np.random.randint(-99,99, size=(n, n)))
funcionalidad_exactitud(A)

La matriz L es inexacta
array([[ 1.        ,  0.        ,  0.        ],
       [-0.05128205,  1.        ,  0.        ],
       [-0.30769231, -0.10126582,  1.        ]])
array([[ 1.        ,  0.        ,  0.        ],
       [-0.05128205,  1.        ,  0.        ],
       [-0.30769231, -0.1031491 ,  1.        ]])
La matriz U inexacta
matrix([[-78,  -4, -75],
        [  0,  79, -55],
        [  0,   0,  35]])
array([[-78.        ,  -4.        , -75.        ],
       [  0.        ,  79.79487179, -55.84615385],
       [  0.        ,   0.        ,  36.1625964 ]])
La matriz P es exacta


En cuanto a la funcionalidad del algoritmo la segunda funcion nos indica que hay errores porque nustro algoritmo no es exacto como el paquete que ya esta implementado en pyhton, por lo que se debe revisar para su mejora.

#Notas
syntax – Is the code well formatted, meeting indentation and whitespace standards and free from parse errors?
style – Is the code idiomatic for the language, are common error-prone patterns for that language avoided, is the code easily understood?
functional – Does the code do what it’s supposed to do?
architecture – Is the code required, are there any improvements to be made through abstractions, reuse of other code. Does the code tie in with the rest of the codebase?