## Algoritmo

Sean $A$ y $A_{11}$ no singulares.

1) Calcular $A_{11}^{-1}A_{12}$ y $A_{11}^{-1}b_1$ teniendo cuidado en no calcular la inversa sino un sistema de ecuaciones lineales:

Para realizar la multiplicación $A_{11}^{-1}b_1$ definimos $y=A_{11}^{-1}b_1$ y por tanto $A_{11}y = b_1$ ($A_{11}$ es no singular). Así, resolvemos para $y$ el sistema anterior y habremos calculado $A_{11}^{-1}b_1$. Similarmente definimos $Y=A_{11}^{-1}A_{12}$ con lo que se tiene $A_{11}Y=A_{12}$. Resolvemos para $Y \in \mathbb{R} ^{n_1 \times n_1}$ y habremos calculado $A_{11}^{-1}A_{12}$.
2) Calcular el complemento de Schur del bloque $A_{11}$ en $A$: $S = A_{22}-A_{21}A_{11}^{-1}A_{12}$. Calcular $ \hat{b} = b_2-A_{21}A_{11}^{-1}b_1$.

3) Resolver $Sx_2 = \hat{b}$.

4) Resolver $A_{11}x_1 = b_1-A_{12}x_2$.

In [2]:
import numpy as np

In [3]:
#Cambiar en el futuro
def nuestro_algoritmo(A, b):
    return np.linalg.solve(A,b)

In [9]:
B =  np.array([[ 1.,  4., -2., -5.],
               [-3.,  9.,  8.,  7.],
               [ 6., -1.,  2.,  8.]])
B.shape[0]

3

In [15]:
B =  np.array([[ 1.,  4., -2., -5.],
               [-3.,  9.,  8.,  7.],
               [ 5.,  1., -6., -4.],
               [ 6., -1.,  2.,  8.]])

B11 = B[:2,:2]
B12 = B[:2,2:]
B21 = B[2:,:2]
B22 = B[2:,2:]

B21

array([[ 5.,  1.],
       [ 6., -1.]])

In [38]:
from math import ceil, floor
#def por_bloques(A, b):
B =  np.array([[ 1.,  4., -2., -5.],
               [-3.,  9.,  8.,  7.],
               [ 5.,  1., -6., -4.],
               [ 5.,  1., -6., -4.],
               [ 6., -1.,  2.,  8.]])
A = B
A_column = A.shape[1]  
A_row = A.shape[0] 
if A_column % 2 == 0:
    x_low  = int(A_column/2)
    x_high = x_low
else:
    x_low = int(ceil(A_column/2))
    x_high = int(floor(A_column/2))

if A_row % 2 == 0:
    y_low  = int(A_row/2)
    y_high = x_low
else:
    y_low = int(ceil(A_row/2))
    y_high = int(floor(A_row/2))

print(x_low, x_high, y_low, y_high)


A11 = A[:y_low,:x_low]
A12 = A[:y_low,x_high:]
A21 = A[y_low:,:x_high]
A22 = A[y_high:,x_high:]

A22
#por_bloques(A, b)   

2 2 3 2


array([[-6., -4.],
       [-6., -4.],
       [ 2.,  8.]])

In [5]:
# Manipulacion de arreglos por bloques
A11 = np.array([[ 1, 4], \
                [-3, 9]], dtype=np.float)
A12 = np.array([[-2,-5], \
                [ 8, 7]], dtype=np.float)
A21 = np.array([[ 5, 1], \
                [ 6,-1]], dtype=np.float)
A22 = np.array([[-6, -4], 
                [ 2, 8]], dtype=np.float)

A = np.block([[A11,A12],
              [A21,A22]])

B =  np.array([[ 1.,  4., -2., -5.],
               [-3.,  9.,  8.,  7.],
               [ 5.,  1., -6., -4.],
               [ 6., -1.,  2.,  8.]])

B11 = B[:2,:2]
B12 = B[:2,2:]
B21 = B[2:,2:]
B22 = B[:2,:2]

b = np.array([3,0,7,6], dtype=np.float)
b1 = b[:2]
b2 = b[2:]

#nuestro_algoritmo(A, b)
#  $A_{11}y = b_1$
A11_b1 = nuestro_algoritmo(A11, b1)
A11_A12 = nuestro_algoritmo(A11, A12)

Schur = A22 - A21@A11_A12
b_hat = b2 - A21@A11_b1

x2 = nuestro_algoritmo(Schur, b_hat)
x1 = nuestro_algoritmo(A11, (b1-A12@x2))

X = np.block([x1,x2])
X


array([ 0.99047619,  0.52539683, -0.36269841,  0.16349206])

In [36]:
# Sí tiene solución
b = np.array([3,0,7,6], dtype=np.float)
x=np.linalg.solve(A,b)
x


array([ 0.99047619,  0.52539683, -0.36269841,  0.16349206])

In [ ]:
# Falta checar que sean no singulares 
# Ideas
det = numpy.linalg.det(A)
if det != 0:
if linalg.cond(x) < 1/sys.float_info.epsilon: