## Algoritmo

Sean $A$ y $A_{11}$ no singulares.

1) Calcular $A_{11}^{-1}A_{12}$ y $A_{11}^{-1}b_1$ teniendo cuidado en no calcular la inversa sino un sistema de ecuaciones lineales:

Para realizar la multiplicación $A_{11}^{-1}b_1$ definimos $y=A_{11}^{-1}b_1$ y por tanto $A_{11}y = b_1$ ($A_{11}$ es no singular). Así, resolvemos para $y$ el sistema anterior y habremos calculado $A_{11}^{-1}b_1$. Similarmente definimos $Y=A_{11}^{-1}A_{12}$ con lo que se tiene $A_{11}Y=A_{12}$. Resolvemos para $Y \in \mathbb{R} ^{n_1 \times n_1}$ y habremos calculado $A_{11}^{-1}A_{12}$.
2) Calcular el complemento de Schur del bloque $A_{11}$ en $A$: $S = A_{22}-A_{21}A_{11}^{-1}A_{12}$. Calcular $ \hat{b} = b_2-A_{21}A_{11}^{-1}b_1$.

3) Resolver $Sx_2 = \hat{b}$.

4) Resolver $A_{11}x_1 = b_1-A_{12}x_2$.

In [27]:
import numpy as np
import sys
sys.path.append('./../')

# OPTIONAL: Load the "autoreload" extension so that code can change
%load_ext autoreload

# OPTIONAL: always reload modules so that as you change code in src, it gets loaded
%autoreload 2
#from src.algorithms import factorizacionPLU
#from src.algorithms import eliminacionPorBloques
import src.algorithms.FactorizacionPLU as plu

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [42]:

#Cambiar en el futuro
def nuestro_algoritmo( A, b):
    return np.linalg.solve(A,b)
    #factorizador = plu.FactorizacionPLU()
    #return factorizador.solve(A,b)

def solve_blocks(A,b):    
    # Check that it is a squared matrix
    A_column = A.shape[1]
    if A_column == A.shape[0]:
        if A_column % 2 == 0:
            x  = int(A_column/2)
        else:
            x = int(ceil(A_column/2))
        print(x)
        A11 = A[:x,:x]
        A12 = A[:x,x:]
        A21 = A[x:,:x]
        A22 = A[x:,x:]

        print(A11)
        print(A12)
        print(A21)
        print(A22)

        b1 = b[:x]
        b2 = b[x:]
        
        A11_b1 = nuestro_algoritmo(A11, b1)
        A11_A12 = nuestro_algoritmo(A11, A12)

        print(A11_b1, A11_A12)
        Schur = A22 - A21@A11_A12
        b_hat = b2 - A21@A11_b1

        x2 = nuestro_algoritmo(Schur, b_hat)
        x1 = nuestro_algoritmo(A11, (b1-A12@x2))

        X = np.block([x1,x2])

    else:
        X = -2
        print("Please enter a squared matrix")
    return X

In [43]:
from math import ceil
#def por_bloques(A, b):
B =  np.array([[ 1.,  4., -2., -5.,1],
               [-3.,  9.,  8.,  7.,2],
               [ 5.,  1., -6., -4.,3],
               [ 5.,  1., -6., -4.,4],
               [ 6., -1.,  2.,  8.,5]])

A =  np.array([[ 1.,  4., -2., -5.],
               [-3.,  9.,  8.,  7.],
               [ 5.,  1., -6., -4.],
               [ 6., -1.,  2.,  8.]])

b = np.array([3,0,7,6,9], dtype=np.float)
a = np.array([3,0,7,6], dtype=np.float)

x_prueba=np.linalg.solve(A,a)
print(x_prueba)

x_nuestra = solve_blocks(A,a)
print(x_nuestra)

x_prueba=np.linalg.solve(B,b)
print(x_prueba)

x_nuestra = solve_blocks(B,b)
print(x_nuestra)


[ 0.99047619  0.52539683 -0.36269841  0.16349206]
2
[[ 1.  4.]
 [-3.  9.]]
[[-2. -5.]
 [ 8.  7.]]
[[ 5.  1.]
 [ 6. -1.]]
[[-6. -4.]
 [ 2.  8.]]
[1.28571429 0.42857143] [[-2.38095238 -3.47619048]
 [ 0.0952381  -0.38095238]]
[ 0.99047619  0.52539683 -0.36269841  0.16349206]
[ 2.24761905  0.67301587  0.26349206  0.08253968 -1.        ]
3
[[ 1.  4. -2.]
 [-3.  9.  8.]
 [ 5.  1. -6.]]
[[-5.  1.]
 [ 7.  2.]
 [-4.  3.]]
[[ 5.  1. -6.]
 [ 6. -1.  2.]]
[[-4.  4.]
 [ 8.  5.]]
[1.3442623  0.42622951 0.02459016] [[ 2.16393443  1.08196721]
 [-0.60655738  0.19672131]
 [ 2.36885246  0.43442623]]
[ 2.24761905  0.67301587  0.26349206  0.08253968 -1.        ]


### Extras

In [ ]:
# Falta checar que sean no singulares 
# Ideas
det = numpy.linalg.det(A)
if det != 0:
if linalg.cond(x) < 1/sys.float_info.epsilon: