In [1]:
import scipy.linalg
import numpy as np

eps = np.finfo(np.float).eps

In [2]:
print('1. Inversa de una matriz')
print('Usa la función lu(A) para obtener la inversa de la matriz')

def inverse(A):
    P, L, U = scipy.linalg.lu(A)
    I = np.eye(len(A))
    res = np.zeros((len(A), len(A)))
    for i in range(len(A)):
        y = np.linalg.solve(L, P @ I[:, i])
        res[i] = np.linalg.solve(U, y)
    return res
A = [[4, -1, 0], [-1, 4, -1], [0, -1, 4]]
print(inverse(A))
print()
print(scipy.linalg.inv(A))

1. Inversa de una matriz
Usa la función lu(A) para obtener la inversa de la matriz
[[0.26785714 0.07142857 0.01785714]
 [0.07142857 0.28571429 0.07142857]
 [0.01785714 0.07142857 0.26785714]]

[[0.26785714 0.07142857 0.01785714]
 [0.07142857 0.28571429 0.07142857]
 [0.01785714 0.07142857 0.26785714]]


In [3]:
def gauss_seidel(a, b):
    d = np.diag(np.diag(a))
    l = np.tril(a, -1)
    m = d + l
    tol = eps
    max = 1000
    i = 0
    x = np.zeros(np.shape(b))
    
    cond = True
    while cond:
        xp = x
        r = b - (np.dot(a, x))
        x = x + np.linalg.solve(m, r)
        i += 1
        cond = np.linalg.norm(np.divide(x - xp, x)) > tol and i < max

    return x, i

In [4]:
print('2. Algoritmo de Gauss-Seidel')
a = np.array([[0.1, 7, -0.3], [3, -0.1, -0.2], [0.3, -0.2, 10]])
b = np.array([-19.3, 7.85, 71.4])
# A = [[3, -0.1, -0.2], [0.1, 7, -0.3], [0.3, -0.2, 10]]
# b = [7.85, -19.3, 71.4]
print('Escribe la matriz P de permutación')
p = np.array([[0, 1, 0], [1, 0, 0], [0, 0, 1]])
print(p)
print('Intercambia los renglones de a y b usando p')
pa = p @ a
pb = p @ b
print(pa)
print(pb)

print('Resuelve el sistema de ecuaciones')
print(gauss_seidel(pa, pb))
print()
print(np.linalg.solve(a, b))

2. Algoritmo de Gauss-Seidel
Escribe la matriz P de permutación
[[0 1 0]
 [1 0 0]
 [0 0 1]]
Intercambia los renglones de a y b usando p
[[ 3.  -0.1 -0.2]
 [ 0.1  7.  -0.3]
 [ 0.3 -0.2 10. ]]
[  7.85 -19.3   71.4 ]
Resuelve el sistema de ecuaciones
(array([ 3. , -2.5,  7. ]), 10)

[ 3.  -2.5  7. ]


In [5]:
def descenso_maximo(A, b, x):
    i = 0
    max = 1000
    tol = eps
    r = b - np.dot(A, x)
    cond = True
    while cond:
        xp = x
        alpha = np.dot(r, r) / (np.transpose(r) @ A @ r)
        x = xp + alpha * r
        r = b - np.dot(A, x)
        i += 1
        cond = np.linalg.norm(np.divide(x - xp, x)) > tol and i < max
    return x, i

In [6]:
def gradiente_conjugado(A, b, x):
    cond = True
    i = 0
    max = 1000
    tol = eps
    r = np.dot(A, x) - b
    p = -r
    while cond:
        xp = x
        alpha = -np.divide(np.dot(np.transpose(r), p), np.transpose(p) @ A @ p)
        x = xp + np.dot(alpha, p)
        r = np.dot(A, x) - b
        B = np.divide(np.transpose(r) @ A @ p, np.transpose(p) @ A @ p)
        p = -r + np.dot(B, p)
        i += 1
        cond = np.linalg.norm(r) > tol and i < max
    return x, i

In [7]:
print('3. Algoritmo de gradiente conjugado')
A = np.array([[4, -1, 0], [-1, 4, -1], [0, -1, 4]])
b = [2, 6, 2]
print(gradiente_conjugado(A, b, [0, 0, 0]))
print()
print(descenso_maximo(A, b, [0, 0, 0]))
print()
print(gauss_seidel(A, b))

print('Gradiente', gradiente_conjugado(A, b, [0, 0, 0])[1], 'vs descenso', descenso_maximo(A, b, [0, 0, 0])[1])

3. Algoritmo de gradiente conjugado
(array([1., 2., 1.]), 2)

(array([1., 2., 1.]), 26)

(array([1., 2., 1.]), 20)
Gradiente 2 vs descenso 26


In [8]:
def newton_rapshon_vv(f, j, x):
    tol = eps
    max = 1000
    cond = True
    i = 0
    while cond:
        xp = x
        x = xp - np.linalg.solve(j(xp), f(xp))
        i += 1
        cond = np.linalg.norm(np.divide(x - xp, x)) > tol and i < max
    return x, i

In [9]:
f = lambda x: [x[0] ** 2 + x[1] ** 2 - 3, x[0] * x[1] - 1]
j = lambda x: [[2 * x[0], 2 * x[1]], [x[1], x[0]]]
print('Primero')
print(newton_rapshon_vv(f, j, [-2, -1]))
print('Segundo')
print(newton_rapshon_vv(f, j, [2, 1]))
print('Tercero')
print(newton_rapshon_vv(f, j, [1, 2]))
print('Cuarto')
print(newton_rapshon_vv(f, j, [-1, -2]))

Primero
(array([-1.61803399, -0.61803399]), 6)
Segundo
(array([1.61803399, 0.61803399]), 6)
Tercero
(array([0.61803399, 1.61803399]), 6)
Cuarto
(array([-0.61803399, -1.61803399]), 6)


In [10]:
print('5. Vectores')
A = lambda a: [2, -3, a]
B = lambda b: [b, 1, -4]
C = lambda c: [3, c, 2]
first = lambda a, b: 2 * b - 3 - 4 * a
second = lambda a, c: 6 - 3 * c + 2 * a
third = lambda b, c: 3 * b + c - 8
a = np.array([[-4, 2, 0], [2, 0, -3], [0, 3, 1]])
b = np.array([3, -6, 10])
p = np.array([[1, 0, 0], [0, 0, 1], [0, 1, 0]])
print(gauss_seidel(p @ a, p @ b))

5. Vectores
(array([0.525, 2.55 , 2.35 ]), 36)


In [11]:
print('6. Uso de Matlab')
A = [[0.1, 7, -0.3], [3, -0.1, -0.2], [0.3, -0.2, 10]]
print(np.append(A, np.eye(len(A)), 1))

6. Uso de Matlab
[[ 0.1  7.  -0.3  1.   0.   0. ]
 [ 3.  -0.1 -0.2  0.   1.   0. ]
 [ 0.3 -0.2 10.   0.   0.   1. ]]
